erika0915/OSP_ewhaMarket

.gitignore
chore: authentication 다시 추가
어떤 변경 사항이 있나요?
=> [Chore] authentication 다시 추가

app.py, templates/products.html, templates/reviews.html
=> chore: 전체 리뷰 조회 임시로 연결함. 함수명+경로 변경

app.py, database.py
=> [Feat] 리뷰 기능 추가 

app.py, templates/product_detail.html, templates/reg_review.html
상품 상세 페이지에서 버튼 클릭 시 리뷰 작성 페이지 렌더링
상품 등록 화면 잘 나오고 상품 등록 화면에 상품명 전달도 완료 ! 
프론트엔드 코드 수정 했는데, 완전히 수정한 거는 아니고 필요한 부분만 수정했어요 ! 
프론트엔드 코드 리팩토링 필요합니당....
어떤 변경 사항이 있나요?
=> [Chore] 리뷰 작성

static/css/products.css, static/js/products.js, templates/products.html
=> products 좋아요 수정

app.py, templates/login.html
=> 로그인 버튼 기능 수정 + flash 기능 추가

static/css/detail.css, templates/product_detail.html
상품 상세 화면 html을 figma에 맞게 수정하였습니다.
어떤 변경 사항이 있나요?
=> Front sharing

static/css/detail.css, static/css/review_detail.css, static/css/style.css, static/js/product_detail.js, static/js/review_detail.js, templates/product_detail.html, templates/review_detail.html
=> 리뷰 상세화면 별점 표기 수정 및 css 이쁘게 고치기

app/auth/routes.py, app/likes/routes.py, database.py, templates/auth/login.html, templates/auth/signup.html, templates/index.html
userId로 변경해서 likes랑 로그인 회원가입 다 변경했습니당 
어떤 변경 사항이 있나요?
=> [Feat] 로그인, 회원가입 부분 수정 

app/reviews/routes.py, database.py
다만, 상품 db 에서 확인하고 싶은데 아직 상품이 미완이라서 기다려야할 듯
어떤 변경 사항이 있나요?
=> [Feat] 리뷰 관련 기능 수정

static/css/mypage.css, static/css/product_detail.css, templates/mypage.html, templates/products/product_detail.html
=> 마이페이지 figma대로 수정 / product_detail.html 원상복구

app/mypage/routes.py, templates/reviews/reg_review.html
어떤 변경 사항이 있나요?
mypage app.py 가 바뀌고 나서 마이페이지 화면이 안 뜨길래 화면 확인하려고 원래대로 코드로 다시 넣었는데 혹시 언니가 다른거 작업하고 있다면 이 부분 머지하지 않아도 돼 ! 그리고 아래 부분도.. 내 파트가 아닌데 일단 리뷰 등록하려고 바꾼거라 ... 마찬가지로 작업하고 있는게 있다면 머지하지 말어유
=> 리뷰 등록 버튼 눌렀을때 화면 뜨게 html 수정

static/css/product_detail.css, templates/products/product_detail.html
=> 제품 상세 페이지 수정

static/css/market.css, templates/market.html
=> 마켓 페이지 css 수정

app/mypage/routes.py, database.py
=> [Chore] 마이페이지에 좋아요 목록 추가

static/css/review_detail.css, templates/reviews/review_detail.html
=> css 잔잔한 수정

static/css/product_detail.css, static/css/review_detail.css, templates/products/product_detail.html, templates/reviews/review_detail.html
=> Chaewon 필요없는 css 대폭 정리했습니다.

static/css/mypage.css, static/css/product_detail.css, static/css/review_detail.css, templates/mypage.html, templates/products/product_detail.html
=> Chaewon 수정사항 반영 ~!

app/mypage/routes.py, app/products/routes.py, database.py, templates/mypage.html
=> 마이페이지에서 사진 누르면 리뷰로 넘어가게

static/css/product_detail.css
=> 상품 상세 내용 자동 줄바꿈 처리 코드 수정

app/likes/routes.py, database.py, templates/products/product_detail.html
=> 마켓페이지 수정 중

templates/mypage.html
=> 판매목록에서 사진 누르면 해당 상세화면으로

database.py
=> [Feat] 좋아요 목록 기능 추가 

app/reviews/routes.py, database.py, templates/reviews/review_detail.html
=> [Chore] 리뷰에 product 관련 데이터 넘겨주기

database.py
=> [Chore] 리뷰 상세 조회에 날짜 변환

app/market/routes.py, database.py, templates/market.html
=> 마켓랭킹 - 마이페이지 연결 다시 추가

static/css/style.css
=> footer 위치 수정

static/css/style.css
=> padding 수정

static/css/mypage.css, templates/mypage.html
=> 좋아요 목록 옆에 하트 추가

static/css/review_detail.css
=> 상세 리뷰 페이지 그림자 없애는게 나은가... 통일성

static/css/review_detail.css
=> 상세 리뷰 페이지 위 간격 통일

static/css/products.css
=> 전체 상품 조희 사이드바 위치 조정

static/css/products.css
=> 전체상품 조희 화면 밑 내용 사진에 맞게 정렬

static/css/mypage.css
=> 좋아요 목록 css 오류 수정

static/css/login.css, static/css/market.css, templates/auth/login.html
=> 로그인 화면 로고 수정
